# Generated by Django 5.2.6 on 2025-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegoodfind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('lost_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
